export const THROTTLER_LIMIT = 'USER_THROTTLER:LIMIT';
export const THROTTLER_TTL = 'USER_THROTTLER:TTL';
export const THROTTLER_TRACKER = 'USER_THROTTLER:TRACKER';
export const THROTTLER_KEY_GENERATOR = 'USER_THROTTLER:KEY_GENERATOR';
export const THROTTLER_OPTIONS = 'USER_THROTTLER:MODULE_OPTIONS';
export const THROTTLER_SKIP = 'USER_THROTTLER:SKIP';
